CONFIG_USB_DEVICE_STACK=y
CONFIG_USB_DEVICE_INITIALIZE_AT_BOOT=n
CONFIG_USB_DEVICE_NETWORK_ECM=n
CONFIG_USB_DEVICE_NETWORK_EEM=n             # interface name is "usb0"
CONFIG_USB_DEVICE_NETWORK_RNDIS=n 
CONFIG_USB_DEVICE_NETWORK_MY_ECM=n
CONFIG_USB_DEVICE_NETWORK_MY_NCM=n
CONFIG_USB_DEVICE_NETWORK_MY_NCM_SIMPLE=y
CONFIG_USB_DEVICE_NETWORK_ECM_MAC="00005e005301"

CONFIG_NET_PKT_RX_COUNT=14
CONFIG_NET_PKT_TX_COUNT=14
CONFIG_NET_BUF_RX_COUNT=28
CONFIG_NET_BUF_TX_COUNT=28
CONFIG_NET_BUF_DATA_SIZE=1500

# not used by application stack sizes
CONFIG_USB_WORKQUEUE_STACK_SIZE=6000
CONFIG_USB_NRFX_WORK_QUEUE_STACK_SIZE=6000

CONFIG_LOG=y
CONFIG_UDC_DRIVER_LOG_LEVEL_WRN=y
CONFIG_USB_DEVICE_LOG_LEVEL_WRN=y
CONFIG_USB_DEVICE_NETWORK_LOG_LEVEL_WRN=y
